### PR TITLE
292b

### PR DESCRIPTION
**Pull request by p01**
:p

### CODE REVIEW

**Comment by xem** [comment]
Thanks! nice tricks.
Actually, I chose the var names "_N" and "$N" to avoid colliding with the user's var names. If we use h i j k, I think it's more risky... To do things right, we should rather run the user's code in an iframe, no?

**Comment by xem** [comment]
also, running the user's code 500 000 times is not optimal, I'm looking for a way to avoid browser freezing, or another approach like "run each snippet for 10 sec and see which one is run the most => this one is the fastest"...
cc @subzey

**Comment by p01** [comment]
Name collisions are less likely now.
As for the core mechanics, well, I just optimized the initial code.

JSPerf does run each version an increasing number of times until it exceeds a given duration or maximum runs, and compute the number of operations per seconds. This would take a lot more than ~292bytes to implement, with a setTimeouts triggering each run and threshold checks, etc...

This is much more elaborate than the initial code of miniJSperf.

**Comment by p01** [comment]
I leave that to you to decide whether you want to continue golfing the initial approach or go closer to the original JSperf

**Comment by xem** [comment]
no, you know what, it's perfect like that :) thanks a lot! I updated the homepage to present the thing a bit better. cheers.

**Pull request merged**
